# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest
  
variables:
  imageName: 'rcmendes/quarkus-redis'
  serviceConnection: 'quayServiceConnection'  

steps:

- task: Maven@3
  inputs:
    options: '-DskipTests -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true -Dquarkus.container-image.builder=jib -Dquarkus.container-image.tag=0.1-alfa -Dquarkus.container-image.registry=quay.io -Dquarkus.container-image.insecure=true -Dquarkus.container-image.group=rcmendes -Dquarkus.container-image.name=quarkus-redis -Dquarkus.container-image.username=$(Username) -Dquarkus.container-image.password=$(QuayPassword)'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '17'
    jdkArchitectureOption: 'x64'
    goals: 'install'    
#- task: Docker@2

#  displayName: Build from Red Hat Universal Base Image
#  inputs:
#    command: build
#    containerRegistry: $(serviceConnection)
#    repository: $(imageName)
#   Dockerfile: src/main/docker/Dockerfile.jvm
#   tags: azure-test
