# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest
  
variables:
  imageName: 'rcmendes/quarkus-redis'
  serviceConnection: 'quayServiceConnection'  

steps:
      
- task: Maven@3
  inputs:
    options: '-DskipTests' 
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '17'
    jdkArchitectureOption: 'x64'
    goals: 'package'

- task: Docker@2
  displayName: Build from Red Hat Universal Base Image
  inputs:
    command: build
    containerRegistry: $(serviceConnection)
    repository: $(imageName)
    Dockerfile: src/main/docker/Dockerfile.jvm
    buildContext: $(System.DefaultWorkingDirectory)
    tags: azure-test
